services:
  - type: web
    name: nba-player-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api.py"
    envVars:
      - key: FLASK_ENV
        value: production
    runtime: python
    pythonVersion: 3.10
